// JS logic as in v2
const state = { inventory: [], selectedBrand: null, search: '', minPrice: null, maxPrice: null, sort: 'featured' };
const grid = document.getElementById('inventoryGrid');
const noResults = document.getElementById('noResults');
const brandChipsEl = document.getElementById('brandChips');
const fmtUSD = (n) => n?.toLocaleString('en-US', { style: 'currency', currency: 'USD', maximumFractionDigits: 0 });
const byId = (id) => document.getElementById(id);
fetch('data/inventory.json').then(r=>r.json()).then(data=>{ state.inventory = data; renderBrandChips(); render(); });
document.getElementById('searchForm').addEventListener('submit', (e)=>{ e.preventDefault(); state.search = document.getElementById('searchInput').value.trim().toLowerCase(); render(); });
byId('sortSelect').addEventListener('change', (e)=>{ state.sort = e.target.value; render(); });
byId('priceApply').addEventListener('click', ()=>{ const minP = parseInt(byId('minPrice').value,10); const maxP = parseInt(byId('maxPrice').value,10); state.minPrice = isNaN(minP)?null:minP; state.maxPrice = isNaN(maxP)?null:maxP; render(); });
document.querySelector('.menu-btn')?.addEventListener('click', (e)=>{ const nav = document.getElementById('main-menu'); const expanded = e.currentTarget.getAttribute('aria-expanded') === 'true'; e.currentTarget.setAttribute('aria-expanded', !expanded); nav.style.display = expanded ? 'none' : 'flex'; });
document.getElementById('year').textContent = new Date().getFullYear();
function renderBrandChips(){ const brands = Array.from(new Set(state.inventory.map(x=>x.make))).sort(); brandChipsEl.innerHTML=''; const all=document.createElement('button'); all.className='chip'+(state.selectedBrand===null?' chip--active':''); all.textContent='All'; all.addEventListener('click',()=>{state.selectedBrand=null; render();}); brandChipsEl.appendChild(all); brands.forEach(b=>{ const btn=document.createElement('button'); btn.className='chip'+(state.selectedBrand===b?' chip--active':''); btn.textContent=b; btn.addEventListener('click',()=>{ state.selectedBrand=(state.selectedBrand===b?null:b); render();}); brandChipsEl.appendChild(btn); });}
function matchesFilters(item){ if(state.selectedBrand && item.make!==state.selectedBrand) return false; if(state.search){ const blob=(item.year+' '+item.make+' '+item.model+' '+(item.trim||'')+' '+(item.features||[]).join(' ')).toLowerCase(); if(!blob.includes(state.search)) return false;} if(state.minPrice!==null && item.price<state.minPrice) return false; if(state.maxPrice!==null && item.price>state.maxPrice) return false; return true; }
function sortItems(items){ switch(state.sort){ case 'price-asc': return items.sort((a,b)=>a.price-b.price); case 'price-desc': return items.sort((a,b)=>b.price-a.price); case 'year-desc': return items.sort((a,b)=>b.year-a.year); case 'year-asc': return items.sort((a,b)=>a.year-b.year); case 'miles-asc': return items.sort((a,b)=>a.miles-b.miles); case 'miles-desc': return items.sort((a,b)=>b.miles-a.miles); default: return items; } }
function render(){ const filtered=state.inventory.filter(matchesFilters); const sorted=sortItems(filtered); grid.innerHTML=''; if(sorted.length===0){ noResults.hidden=false; return; } noResults.hidden=true; for(const car of sorted){ const card=document.createElement('article'); card.className='card-vehicle'; const img=document.createElement('img'); img.alt=`${car.year} ${car.make} ${car.model}`; img.src=car.image || 'assets/placeholder.jpg'; card.appendChild(img); const body=document.createElement('div'); body.className='card-vehicle__body'; const title=document.createElement('h3'); title.className='card-vehicle__title'; title.textContent=`${car.year} ${car.make} ${car.model}${car.trim?' '+car.trim:''}`; const meta=document.createElement('div'); meta.className='card-vehicle__meta'; meta.textContent=`${car.miles.toLocaleString()} mi • ${car.drivetrain||'FWD'} • ${car.transmission||'Auto'}`; const price=document.createElement('div'); price.className='card-vehicle__price'; price.textContent=fmtUSD(car.price); const btn=document.createElement('a'); btn.href='#contact'; btn.className='btn btn--small'; btn.style.marginTop='.7rem'; btn.textContent='View / Reserve'; body.append(title, meta, price, btn); card.appendChild(body); grid.appendChild(card);} }
document.getElementById('sellForm').addEventListener('submit',(e)=>{ e.preventDefault(); const formData=new FormData(e.currentTarget); const obj=Object.fromEntries(formData.entries()); const key='eda_sell_leads'; const leads=JSON.parse(localStorage.getItem(key)||'[]'); leads.push({...obj, ts:new Date().toISOString()}); localStorage.setItem(key, JSON.stringify(leads)); alert('Thanks! We will contact you shortly.'); e.currentTarget.reset(); });
